Form branch with 3 ways of forms.
AhmedAmin90/rails_form pull request #2
Opened 2021-01-26 20:26 UTC by AhmedAmin90

In this branch, I used 3 ways to build a form in rails that can send parameters to a controller so that it can build an instance of a model with those parameters.
By this form I can create new users and edit these users information.

2021-01-26 22:07 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @AhmedAmin90 :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] To be able to run the project, you can make sure that you change the name of the table from `:user` to `:users` for migrations
- [x] Learn about the inline comments
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-01-26 22:07 UTC, descholar-ceo commented on app/views/users/new.html.erb
> +<%= form_tag("/users") do %>
[required] Replace `/users` with `users_path`

2021-01-26 23:14 UTC, AhmedAmin90 commented
@descholar-ceo  Thanks a lot for your positive comments, I did the required changes and I am trying to submit a new code review but the dashboard told me: Project You already have an open code review request for Forms. Is there a new way for code review or there is a problem in the system?

2021-01-27 05:46 UTC, descholar-ceo commented
> @descholar-ceo Thanks a lot for your positive comments, I did the required changes and I am trying to submit a new code review but the dashboard told me: Project You already have an open code review request for Forms. Is there a new way for code review or there is a problem in the system?

@AhmedAmin90 Sorry for that inconvenient experience I think now it's fixed

2021-01-27 10:00 UTC, mimipeshy commented
### STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hey there @AhmedAmin90: wave: Great job on working on the feedback given, however, one more change in order to mark this project approved,

- [ ] You need to comment out form_tag in views/users/new as from this ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

That's all :smile: , kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

2021-01-27 10:29 UTC, AhmedAmin90 commented
Thanks, @mimipeshy for your feedback, I changed it, but I was using (if false) way to comment out form_tag as this reference: https://stackoverflow.com/questions/3901619/how-to-comment-lines-in-rails-html-erb-files/13603081

2021-01-27 10:33 UTC, mimipeshy commented
### STATUS :APPROVED :partying_face: 

Hey @AhmedAmin90 thanks for the feedback as well, I will take note of it:smile:  This project is therefore approved. Go ahead and merge. All the best and Happy Coding :computer: 

Regards
Peris Ndanu

2021-01-27 10:38 UTC, AhmedAmin90 commented
Thanks a lot :star: :relaxed: @mimipeshy

2021-01-27 10:38 UTC, merged